name: Structure Data Preview
on:
  pull_request:
    branches: master
jobs:
    deploy_preview:
        runs-on: ubuntu-latest
        name: Deploy the Pull Request Preview
        outputs:
          url: ${{ steps.netlify-deploy.outputs.deploy-url }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v1
          - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
              node-version: 12.x
          - name: install n build
            env:
                SANITY_DEPLOY_STUDIO_TOKEN: ${{secrets.SANITY_AUTH_TOKEN}}
            run: |
                 yarn
                 npm run build-web
          - name: Deploy to Netlify
            id: netlify-deploy
            uses: nwtgck/actions-netlify@v1.1
            with:
                publish-dir: 'packages/tl-ph/public'
                github-token: ${{ secrets.GITHUB_TOKEN }}
                deploy-message: ${{ github.event.pull_request.title }}
            env:
              NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WEB_SITE_ID }}
          - run: echo netlify URL ${{ steps.netlify-deploy.outputs.deploy-url }}      
    sdtt:
      runs-on: ubuntu-latest
      name: Run axe Data Tests
      needs: [deploy_preview]
      steps:
          - name: Run axe Data Test
            run: |
                 npm install pa11y-ci
                 pa11y ${{ needs.deploy_preview.outputs.url }} 
